import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vijay
 */
public class addmember extends javax.swing.JFrame {

    /**
     * Creates new form addmember
     */
    public addmember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel57 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        txtMNo = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtMAdd = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtMPh = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        txtMFee = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        txtMDate = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txtMStatus = new javax.swing.JTextField();
        cmdUpdate = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        cmdExit3 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMIS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Console");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setBackground(new java.awt.Color(153, 204, 255));
        jLabel57.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Select a Member");
        jLabel57.setOpaque(true);
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        list.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        list.setModel(new DefaultListModel());
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(list);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 158, 257));

        txtMNo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 61, 83, 32));

        jLabel58.setBackground(new java.awt.Color(153, 204, 255));
        jLabel58.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel58.setText("Member No.");
        jLabel58.setOpaque(true);
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 66, -1, -1));

        jLabel59.setBackground(new java.awt.Color(153, 204, 255));
        jLabel59.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel59.setText("Name");
        jLabel59.setOpaque(true);
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 109, -1, -1));

        txtMName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNameActionPerformed(evt);
            }
        });
        txtMName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtMNamePropertyChange(evt);
            }
        });
        txtMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 104, 227, 32));

        jLabel60.setBackground(new java.awt.Color(153, 204, 255));
        jLabel60.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel60.setText("Address");
        jLabel60.setOpaque(true);
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 147, -1, -1));

        txtMAdd.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAddActionPerformed(evt);
            }
        });
        getContentPane().add(txtMAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 142, 227, 32));

        jLabel61.setBackground(new java.awt.Color(153, 204, 255));
        jLabel61.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel61.setText("Phone/Mobile");
        jLabel61.setOpaque(true);
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 185, -1, -1));

        txtMPh.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMPh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMPh, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 180, 227, 32));

        jLabel62.setBackground(new java.awt.Color(153, 204, 255));
        jLabel62.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel62.setText("Membership Fee");
        jLabel62.setOpaque(true);
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 244, -1, -1));

        txtMFee.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMFee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 239, 227, 32));

        jLabel63.setBackground(new java.awt.Color(153, 204, 255));
        jLabel63.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel63.setText("Membership Date");
        jLabel63.setOpaque(true);
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 291, -1, -1));

        txtMDate.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 286, 227, 32));

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 324, 90, -1));

        jLabel65.setBackground(new java.awt.Color(153, 204, 255));
        jLabel65.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jLabel65.setText("Status");
        jLabel65.setOpaque(true);
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 351, -1, -1));

        txtMStatus.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 350, 70, -1));

        cmdUpdate.setBackground(new java.awt.Color(0, 51, 255));
        cmdUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(cmdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 122, 40));

        cmdDelete.setBackground(new java.awt.Color(0, 51, 255));
        cmdDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdDelete.setText("Delete");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 127, 40));

        cmdExit3.setBackground(new java.awt.Color(0, 51, 255));
        cmdExit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdExit3.setText("Exit");
        cmdExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExit3ActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 110, 40));

        jButton17.setBackground(new java.awt.Color(0, 51, 255));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setText("BACK TO MAIN FORM");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 221, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD MEMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton18.setText("SAVE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 88, -1, -1));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel3.setText("MEMBER CONSOLE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 250, -1));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ISSUE_STATUS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 347, -1, -1));

        txtMIS.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(txtMIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 344, 119, 27));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 675, 10));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/77.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 680, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement stmt;
ResultSet rs;
String sql = "SELECT * FROM Member;";
    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // getSelectedValue() method extracts the current cursor location value into a variable
        String MembNo = (String) list.getSelectedValue();
        // Extract the first 4 characters as Member No into a variable
        String Mno =MembNo.trim().substring(0, 4);
        String query = "SELECT * FROM Member WHERE memb_no = " + (Mno) + ";";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","blue");
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                //  String Mno=rs.getString("memb_no");
                String MName = rs.getString("memb_name");
                String MAdd = rs.getString("memb_add");
                String MPh1 = rs.getString("memb_phone");
                String MDate = rs.getString("mdate");
                // String MEDate = rs.getString("medate");
                String MFee = rs.getString("mfee");
                String MStatus = rs.getString("mem_status");
                String MIssue = rs.getString("mem_issue");

                // Displaying the contents in respective text boxes.
                txtMNo.setText(Mno);
                txtMName.setText(MName);
                txtMAdd.setText(MAdd);
                txtMPh.setText(MPh1);
                txtMDate.setText(MDate);
                txtMFee.setText(MFee);
                txtMStatus.setText(MStatus);
                // txtMStatus.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Record does not found in Member table");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_listMouseClicked

    private void txtMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNameActionPerformed

    }//GEN-LAST:event_txtMNameActionPerformed

    private void txtMNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtMNamePropertyChange

    }//GEN-LAST:event_txtMNamePropertyChange

    private void txtMNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMNameKeyPressed

    }//GEN-LAST:event_txtMNameKeyPressed

    private void txtMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAddActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","blue");
            Statement stmt = con.createStatement();
            String sql="SELECT * FROM MEMBER;";
            ResultSet rs = stmt.executeQuery(sql);
            int Mno = Integer.parseInt(txtMNo.getText().trim());
            // Steps to confirm deletion
            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to updare this record ?");
            if (opt == JOptionPane.YES_OPTION) {
                try {

                    String MName = txtMName.getText();
                    String MAdd = txtMAdd.getText();
                    String MPh1 = txtMPh.getText();
                    String MDate = txtMDate.getText();
                    String MEDate = txtMDate.getText();
                    double MFee = Double.parseDouble(txtMFee.getText());
                    // Member table
                    String strSQL = "Update Member set memb_name ='"+(MName)+"', memb_add = '"+(MAdd)+"', memb_phone = '"+(MPh1)+"', mdate = '"+(MDate)+"', mfee = "+(MFee)+" where memb_no = " + (Mno);
                    int rowsEffected = stmt.executeUpdate(strSQL);

                    if (rowsEffected == 0)
                    JOptionPane.showMessageDialog(this, "Record does not exists");
                    else {
                        JOptionPane.showMessageDialog(this,"Record updated");
                        // Text boxes cleared
                        txtMNo.setText("");
                        txtMName.setText("");
                        txtMAdd.setText("");
                        txtMPh.setText("");
                        txtMDate.setText("");
                        txtMFee.setText("");
                        txtMStatus.setText("");
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unable to update");
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","blue");
            stmt = con.createStatement();
            String sql="SELECT * FROM MEMBER;";
            rs = stmt.executeQuery(sql);
            int Mno = Integer.parseInt(txtMNo.getText().trim());
            // Steps to confirm deletion
            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete this record ?");
            if (opt == JOptionPane.YES_OPTION) {
                try {
                    // Member table
                    String strSQL = "delete from member where memb_no="+Mno ;
                    int rowsEffected = stmt.executeUpdate(strSQL);

                    if (rowsEffected == 0)
                    JOptionPane.showMessageDialog(this, "Record does not exists");
                    else {
                        JOptionPane.showMessageDialog(this,"Record Deleted");
                        // Text boxes cleared
                        txtMNo.setText("");
                        txtMName.setText("");
                        txtMAdd.setText("");
                        txtMPh.setText("");
                        txtMDate.setText("");
                        txtMFee.setText("");
                        txtMStatus.setText("");
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unable to delete");
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void cmdExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExit3ActionPerformed
      System.exit(0);

    }//GEN-LAST:event_cmdExit3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new first().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtMStatus.setText("0");
        jButton18.setEnabled(true);
        try {
            //REGISTER
            Class.forName("com.mysql.jdbc.Driver");
            //Class.forName("java.sql.driver");

            //CONNECTION
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","blue");

            //EXECUTE QUERY
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            //for memb no
            int MNO=1000, Mno = 0;
            while (rs.next()) {
                MNO = rs.getInt("memb_no");
            }
            MNO++;
            Mno = MNO;
            txtMNo.setText(Integer.toString(Mno));
            //for status
           // jTextField8.setText(Integer.toString(Mno+100));
            txtMName.setFocusable(true);
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null ,e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
txtMNo.setText(" ");
txtMName.setText(" ");
txtMAdd.setText(" ");
txtMPh.setText(" ");
txtMFee.setText(" ");
txtMDate.setText(" ");
txtMStatus.setText(" ");
txtMIS.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try{
            //REGISTER
            Class.forName("com.mysql.jdbc.Driver");
            //Class.forName("java.sql.driver");

            //CONNECTION
            String db_url="jdbc:mysql://localhost:3306/project";
            String pwd="blue";
            String user="root";

            Connection conn=(Connection)DriverManager.getConnection(db_url,user,pwd);

            //EXECUTED QUERIES
            stmt=conn.createStatement();

            rs=stmt.executeQuery(sql);
            int no=Integer.parseInt(txtMNo.getText());
            String name=txtMName.getText();
            String add1=txtMAdd.getText();

            String date=txtMDate.getText();
            String status=txtMStatus.getText();
            String issue=txtMIS.getText();
            String pno=txtMPh.getText();
            double fee = Double.parseDouble(txtMFee.getText());
            System.out.print(1);

            int then=JOptionPane.showConfirmDialog(null,"ARE YOU REALLY WANT TO BECOME MEMBER","FOR CONFORMATION",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if(then==JOptionPane.YES_OPTION){
                System.out.print(9);
                String ssql="INSERT INTO Member(memb_no, memb_name, memb_add, mdate, mfee, mem_status, mem_issue, MEMb_phone)values("+(no)+", '"+(name)+"', '"+(add1)+"', '"+(date)+"',"+(fee)+", "+(status)+", '"+(issue)+"', '"+(pno)+"');";
                System.out.print(8);
                stmt.executeUpdate(ssql);
                System.out.print(9);
                JOptionPane.showMessageDialog(this,"YOUR USER NAME IS:"+name+"  YOUR I.D NO IS:"+status);
            }

            jButton18.setEnabled(false);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        txtMNo.setEditable(false);
      
        txtMStatus.setEditable(false);
        // Creating a ListModel object dModel to perform DefaultListModel
        // method operations
        DefaultListModel dModel = (DefaultListModel) list.getModel();
        // Method to add elements into jList1 control
        dModel.clear();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","blue");
            stmt = con.createStatement();
            String SQL = "SELECT * FROM Member";
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String Mno = rs.getString("memb_no");
                String MName = rs.getString("memb_name");
                // To make the Member no. as 4 digit because we will extract 4 digit from list value
		// in mouse click event.

               dModel.addElement(Mno + "- " + MName);
                }

              list.setModel(dModel);
        }


    catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdExit3;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList list;
    private javax.swing.JTextField txtMAdd;
    private javax.swing.JTextField txtMDate;
    private javax.swing.JTextField txtMFee;
    private javax.swing.JTextField txtMIS;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMNo;
    private javax.swing.JTextField txtMPh;
    private javax.swing.JTextField txtMStatus;
    // End of variables declaration//GEN-END:variables
}
