
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vijay
 */
public class addVehicle extends javax.swing.JFrame {

    /**
     * Creates new form addVehicle
     */
    public addVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jvehno = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jvehname = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jod1 = new javax.swing.JTextField();
        jod2 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jistatus = new javax.swing.JTextField();
        model = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jprice = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jcapacity = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jbatch = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jpurchase = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jbooking = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jstatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        cmdNew = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        cmdExit2 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD VEHICLE");

        jPanel8.setBackground(new java.awt.Color(51, 102, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(545, 676));
        jPanel8.setLayout(null);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Vehicle  No.");
        jPanel8.add(jLabel44);
        jLabel44.setBounds(10, 40, 70, 17);

        jvehno.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jvehno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jvehno.setDisabledTextColor(new java.awt.Color(51, 153, 0));
        jvehno.setEnabled(false);
        jvehno.setFocusable(false);
        jvehno.setRequestFocusEnabled(false);
        jPanel8.add(jvehno);
        jvehno.setBounds(180, 40, 67, 26);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Vehicle Name");
        jPanel8.add(jLabel45);
        jLabel45.setBounds(10, 80, 80, 17);

        jvehname.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jvehname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jvehname);
        jvehname.setBounds(181, 75, 291, 26);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Other Discriptions");
        jPanel8.add(jLabel46);
        jLabel46.setBounds(0, 120, 108, 17);

        jod1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jod1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jod1);
        jod1.setBounds(181, 112, 290, 26);

        jod2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jod2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jod2);
        jod2.setBounds(181, 149, 290, 26);

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("ISSUE STATUS");
        jPanel8.add(jLabel53);
        jLabel53.setBounds(0, 193, 90, 17);

        jistatus.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jistatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jistatus);
        jistatus.setBounds(181, 193, 146, 26);

        model.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        model.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAR", "TRUCK", "BUS ", "VAN" }));
        jPanel8.add(model);
        model.setBounds(181, 230, 231, 26);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Type");
        jPanel8.add(jLabel47);
        jLabel47.setBounds(0, 235, 31, 17);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Price");
        jPanel8.add(jLabel48);
        jLabel48.setBounds(2, 272, 29, 17);

        jprice.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jprice);
        jprice.setBounds(181, 267, 300, 26);

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Engine capacity (in L)");
        jPanel8.add(jLabel52);
        jLabel52.setBounds(1, 316, 131, 17);

        jcapacity.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jcapacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jcapacity);
        jcapacity.setBounds(181, 311, 300, 26);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Batch No.");
        jPanel8.add(jLabel54);
        jLabel54.setBounds(1, 353, 60, 17);

        jbatch.setEditable(false);
        jbatch.setBackground(new java.awt.Color(255, 255, 255));
        jbatch.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jbatch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbatch.setDisabledTextColor(new java.awt.Color(0, 102, 0));
        jbatch.setEnabled(false);
        jbatch.setFocusable(false);
        jPanel8.add(jbatch);
        jbatch.setBounds(181, 348, 300, 26);

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Purchase Date");
        jPanel8.add(jLabel49);
        jLabel49.setBounds(1, 473, 89, 17);

        jpurchase.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jpurchase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jpurchase);
        jpurchase.setBounds(181, 468, 290, 26);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("(YYYY-MM-DD)");
        jPanel8.add(jLabel50);
        jLabel50.setBounds(181, 500, 80, 13);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Price For Booking");
        jPanel8.add(jLabel51);
        jLabel51.setBounds(1, 429, 106, 17);

        jbooking.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jbooking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jbooking);
        jbooking.setBounds(181, 424, 78, 26);

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Status");
        jPanel8.add(jLabel55);
        jLabel55.setBounds(1, 397, 39, 17);

        jstatus.setEditable(false);
        jstatus.setBackground(new java.awt.Color(255, 255, 255));
        jstatus.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jstatus.setDisabledTextColor(new java.awt.Color(0, 153, 0));
        jstatus.setEnabled(false);
        jstatus.setFocusable(false);
        jPanel8.add(jstatus);
        jstatus.setBounds(181, 392, 78, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1-iphone-6-wallpaper-hd-ios8-color-triflat.jpg"))); // NOI18N
        jPanel8.add(jLabel2);
        jLabel2.setBounds(0, -10, 510, 540);

        jPanel13.setBackground(new java.awt.Color(0, 102, 204));

        cmdNew.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        cmdNew.setText("New");
        cmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNewActionPerformed(evt);
            }
        });

        cmdSave.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdClear.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        cmdClear.setText("Clear");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton16.setText("BACK TO MAIN FORM");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        cmdExit2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        cmdExit2.setText("Exit");
        cmdExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(cmdNew, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(cmdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdNew, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel56.setBackground(new java.awt.Color(0, 51, 204));
        jLabel56.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("VEHICLE ");
        jLabel56.setOpaque(true);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e38decb419b3551f15add1a215ac9c48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNewActionPerformed
        jistatus.setText("NON");
        cmdSave.setEnabled(true);

        try {
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt = con.createStatement();
            String sql="SELECT * FROM VEH;";
            ResultSet rs = stmt.executeQuery(sql);
            int MNO=9000, Mno = 0;
            while (rs.next()) {
                MNO = rs.getInt("V_no");
            }
            MNO++;
            Mno = MNO;
            jvehno.setText(Integer.toString(Mno));
            //for status
            jstatus.setText(Integer.toString(Mno+100));

            Statement stmt1 = con.createStatement();
            String SQL1 = "SELECT * FROM VEH_TYPE";// To list publishers in JComboBox1 component
            ResultSet rs1 = stmt1.executeQuery(SQL1);
            while (rs1.next())
            {
                String tno = rs1.getString("type_no");
                String tName = rs1.getString("type_name");

                if (tno.length() < 4)
                {
                    int x = tno.length();
                    int nl = 4 - x;
                    while (nl > 0)
                    {
                        tno = tno + " ";
                        nl--;
                    }
                    jbatch.setText(tno);
                }
                model.addItem(tno + "- " + tName);
                // jbatch.setText(tno);
            }

            jvehname.setFocusable(true);
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null ,e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");

        }
    }//GEN-LAST:event_cmdNewActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed

        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt = con.createStatement();
            String sql="SELECT * FROM MEMBER;";
            ResultSet rs = stmt.executeQuery(sql);

            int no=Integer.parseInt(jvehno.getText());
            String name=jvehname.getText();
            String dis1=jod1.getText();
            String dis2=jod2.getText();
            int price=Integer.parseInt(jprice.getText());
            String cap=jcapacity.getText();
            String bno=jbatch.getText();
            String date=jpurchase.getText();
            int pbook=Integer.parseInt(jbooking.getText());
            int status=Integer.parseInt(jstatus.getText());
            Object type=model.getSelectedItem();
            String ISSUE=jistatus.getText();
            int then=JOptionPane.showConfirmDialog(this,"ARE YOU REALLY WANT TO SAVE THIS RECORD","FOR CONFORMATION",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if(then==JOptionPane.YES_OPTION){
                String ssql="INSERT INTO VEH(v_no, v_name, oth_disc ,type , price, v_cap, batchno, pdate, rs_book , status ,issue_status)values("+(no)+", '"+(name)+"', '"+(dis1+dis2)+"', '"+(type)+"', "+(price)+", '"+(cap)+"',  '"+(bno)+"', '"+(date)+"', "+(pbook)+", "+(status)+",'"+ISSUE+"');";
                int rowsEffected = stmt.executeUpdate(ssql);
                JOptionPane.showMessageDialog(this," THE NEW VEHICLE IS ADDED TO RECORD "+'\n'+ "ALL TRANSACTION WITH DATABASE IS DONE","",JOptionPane.INFORMATION_MESSAGE );
                String sp="INSERT INTO VEH_TYPE values("+no+",'"+name+"','"+(dis1+dis2)+"');";
                 int rows = stmt.executeUpdate(sp);
            }

            cmdSave.setEnabled(false);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");

        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        jvehname.setText("");
        jvehno.setText("");
        jod2.setText("");
        jprice.setText("");
      jcapacity.setText("");
        jvehname.setText("");
     jstatus.setText("");
     jbooking.setText("");
     jpurchase.setText("");
        jod1.setText("");
        cmdSave.setEnabled(false);
        
    }//GEN-LAST:event_cmdClearActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        new   first().setVisible(true);
      new  addVehicle().setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void cmdExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExit2ActionPerformed
       new addVehicle().setVisible(false);
    }//GEN-LAST:event_cmdExit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdExit2;
    private javax.swing.JButton cmdNew;
    private javax.swing.JButton cmdSave;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JTextField jbatch;
    private javax.swing.JTextField jbooking;
    private javax.swing.JTextField jcapacity;
    private javax.swing.JTextField jistatus;
    private javax.swing.JTextField jod1;
    private javax.swing.JTextField jod2;
    private javax.swing.JTextField jprice;
    private javax.swing.JTextField jpurchase;
    private javax.swing.JTextField jstatus;
    private javax.swing.JTextField jvehname;
    private javax.swing.JTextField jvehno;
    private javax.swing.JComboBox model;
    // End of variables declaration//GEN-END:variables
}
