import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vijay
 */
public class vehicleInformation extends javax.swing.JFrame {

    /**
     * Creates new form vehicleInformation
     */
    public vehicleInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cmdFirst = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();
        cmdPrev = new javax.swing.JButton();
        cmdLast = new javax.swing.JButton();
        GETREC = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VEHICLE INFORMATION");

        lb1.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("VEHICLE INFORMATION");

        lb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb2.setText("PLEASE WRITE THE VEH NO OF THE VEH TO GET ITS RECORD");

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("VEH NO");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(21, 21, 43, 15);

        tf3.setEditable(false);
        tf3.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        tf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(tf3);
        tf3.setBounds(168, 13, 182, 32);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("VEH NAME");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(21, 60, 59, 15);

        tf4.setEditable(false);
        tf4.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        tf4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(tf4);
        tf4.setBounds(168, 51, 182, 33);

        tf6.setEditable(false);
        tf6.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        tf6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(tf6);
        tf6.setBounds(168, 102, 182, 32);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("TYPE");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(21, 111, 27, 14);

        tf7.setEditable(false);
        tf7.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        tf7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(tf7);
        tf7.setBounds(168, 145, 182, 29);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("PRICE");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(21, 145, 34, 29);

        tf8.setEditable(false);
        tf8.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        tf8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(tf8);
        tf8.setBounds(168, 192, 182, 32);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("VEH CAPACITY(IN L)");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(21, 200, 112, 15);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1-iphone-6-wallpaper-hd-ios8-color-triflat.jpg"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 380, 270);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("BATCH NO");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 32, 55, 14);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("PURCHASE DATE");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 70, 91, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("BOOKING PRICE(\\DAY)");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(10, 108, 125, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("ISSUE STATUS");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(10, 152, 80, 14);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField7);
        jTextField7.setBounds(155, 23, 140, 32);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField8);
        jTextField8.setBounds(155, 61, 140, 31);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField9);
        jTextField9.setBounds(153, 98, 142, 34);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField11);
        jTextField11.setBounds(155, 143, 140, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/77.jpg"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 320, 270);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        cmdFirst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdFirst.setText("First");
        cmdFirst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFirstActionPerformed(evt);
            }
        });

        cmdNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdNext.setText("Next");
        cmdNext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextActionPerformed(evt);
            }
        });

        cmdPrev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdPrev.setText("Previous");
        cmdPrev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrevActionPerformed(evt);
            }
        });

        cmdLast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdLast.setText("Last");
        cmdLast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLastActionPerformed(evt);
            }
        });

        GETREC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GETREC.setText("GET RECORD");
        GETREC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GETREC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETRECActionPerformed(evt);
            }
        });

        cmdExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdExit.setText("Exit");
        cmdExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cmdLast, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(GETREC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GETREC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(212, 212, 212)
                                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(lb2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void cmdFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFirstActionPerformed

        try{

            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt =(Statement)con.createStatement();
            String query="select * from veh;";
            ResultSet rs= stmt.executeQuery(query);
            if (rs.first()) {
                String no = rs.getString("v_no");
                String name = rs.getString("V_name");
                String disc = rs.getString("oth_disc");
                String type = rs.getString("type");
                String price = rs.getString("price");
                String cap = rs.getString("v_cap");
                String batchno = rs.getString("batchno");
                String date = rs.getString("pdate");
                String bPrice = rs.getString("rs_book");
                String st = rs.getString("status");
                String issue= rs.getString("issue_status");

                tf2.setText(""+no);
                tf3.setText(""+no);
                tf4.setText(""+name);

                tf6.setText(""+type);
                tf7.setText(""+price);
                tf8.setText(""+cap);
                jTextField7.setText(""+batchno);
                jTextField8.setText(""+date);
                jTextField9.setText(""+bPrice);
                //  jTextField10.setText(""+st);
                jTextField11.setText(""+issue);
            }
            else
            {
                cmdFirst.setEnabled(false);
                cmdNext.setEnabled(false);
                cmdPrev.setEnabled(false);
                cmdLast.setEnabled(false);
                JOptionPane.showMessageDialog(this, "THERE IS NO RECORD IN TABLE", "DEAR USER",0);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdFirstActionPerformed

    private void cmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextActionPerformed
//Coding for NEXT BUTTON
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt =(Statement)con.createStatement();
            String n=Integer.toString(Integer.parseInt(tf2.getText())+1);
            String query="select * from veh where v_no="+tf2.getText()+" and v_no="+n+";";
            ResultSet rs= stmt.executeQuery(query);
               if(rs.next()) {
                String no = rs.getString("v_no");
                String name = rs.getString("V_name");
                String disc = rs.getString("oth_disc");
                String type = rs.getString("type");
                String price = rs.getString("price");
                String cap = rs.getString("v_cap");
                String batchno = rs.getString("batchno");
                String date = rs.getString("pdate");
                String bPrice = rs.getString("rs_book");
                String st = rs.getString("status");
                String issue= rs.getString("issue_status");
              
                tf2.setText(""+no);
                tf3.setText(""+no);
                
                tf6.setText(""+type);
                tf7.setText(""+price);
                tf8.setText(""+cap);
                jTextField7.setText(""+batchno);
                jTextField8.setText(""+date);
                jTextField9.setText(""+bPrice);
          
                jTextField11.setText(""+issue);

                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(true);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(true);

            }
            else
            {

                cmdNext.setEnabled(false);
                JOptionPane.showMessageDialog(this, "You are at last record position", "user",0);

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdNextActionPerformed

    private void cmdPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrevActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt =(Statement)con.createStatement();
            String query="select * from veh;";
            ResultSet rs= stmt.executeQuery(query);

            if (rs.previous()) {
                String no = rs.getString("v_no");
                String name = rs.getString("V_name");
                String disc = rs.getString("oth_disc");
                String type = rs.getString("type");
                String price = rs.getString("price");
                String cap = rs.getString("v_cap");
                String batchno = rs.getString("batchno");
                String date = rs.getString("pdate");
                String bPrice = rs.getString("rs_book");
                String st = rs.getString("status");
                String issue= rs.getString("issue_status");
                //System.out.println(Acno + "|" + bTitle + "|" + Auth1 + "|" + Price + "|" + edition);
                tf2.setText(""+no);
                tf3.setText(""+no);
                tf4.setText(""+name);
                // tf5.setText(""+disc);
                tf6.setText(""+type);
                tf7.setText(""+price);
                tf8.setText(""+cap);
                jTextField7.setText(""+batchno);
                jTextField8.setText(""+date);
                jTextField9.setText(""+bPrice);
                //  jTextField10.setText(""+st);
                jTextField11.setText(""+issue);

                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(true);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(true);

            }
            else
            {
                cmdPrev.setEnabled(false);
                cmdNext.setEnabled(true);
                JOptionPane.showMessageDialog(this, "YOU ARE AT FIRST RECORD", "DEAR USER",0);
            }

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdPrevActionPerformed

    private void cmdLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLastActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt =(Statement)con.createStatement();
            String query="select * from veh;";
            ResultSet rs= stmt.executeQuery(query);

            if (rs.last()) {
                String no = rs.getString("v_no");
                String name = rs.getString("V_name");
                String disc = rs.getString("oth_disc");
                String type = rs.getString("type");
                String price = rs.getString("price");
                String cap = rs.getString("v_cap");
                String batchno = rs.getString("batchno");
                String date = rs.getString("pdate");
                String bPrice = rs.getString("rs_book");
                String st = rs.getString("status");
                String issue= rs.getString("issue_status");
                //System.out.println(Acno + "|" + bTitle + "|" + Auth1 + "|" + Price + "|" + edition);
                tf2.setText(""+no);
                tf3.setText(""+no);
                tf4.setText(""+name);
                // tf5.setText(""+disc);
                tf6.setText(""+type);
                tf7.setText(""+price);
                tf8.setText(""+cap);
                jTextField7.setText(""+batchno);
                jTextField8.setText(""+date);
                jTextField9.setText(""+bPrice);
                // jTextField10.setText(""+st);
                jTextField11.setText(""+issue);

                cmdFirst.setEnabled(true);
                cmdNext.setEnabled(false);
                cmdPrev.setEnabled(true);
                cmdLast.setEnabled(false);

            }
            else {
                JOptionPane.showMessageDialog(this, "YOU ARE ALREADY AT LAST RECORD", "DEAR USER",0);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdLastActionPerformed

    private void GETRECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETRECActionPerformed
        String num=tf2.getText();
        try {
            Class.forName("java.sql.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root", "blue");
            Statement stmt =(Statement)con.createStatement();
            ResultSet rs=stmt.executeQuery( "SELECT * FROM VEH WHERE V_NO="+num+";");

            if (rs.next()) {
                String no = rs.getString("v_no");
                String name = rs.getString("V_name");
                String disc = rs.getString("oth_disc");
                String type = rs.getString("type");
                String price = rs.getString("price");
                String cap = rs.getString("v_cap");
                String batchno = rs.getString("batchno");
                String date = rs.getString("pdate");
                String bPrice = rs.getString("rs_book");
                String st = rs.getString("status");
                String issue= rs.getString("issue_status");
                //System.out.println(Acno + "|" + bTitle + "|" + Auth1 + "|" + Price + "|" + edition);
                tf2.setText(""+no);
                tf3.setText(""+no);
                tf4.setText(""+name);
                // tf5.setText(""+disc);
                tf6.setText(""+type);
                tf7.setText(""+price);
                tf8.setText(""+cap);
                jTextField7.setText(""+batchno);
                jTextField8.setText(""+date);
                jTextField9.setText(""+bPrice);
                // jTextField10.setText(""+st);
                jTextField11.setText(""+issue);
            } else {
                JOptionPane.showMessageDialog(null, "RECORD DOES NOT FOUND IN VEH TABLE"+'\n'+"THE VEH_NO IS WRONG");
            }

        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()+"  "+'\n' + " YOU HAVE AN ERROR IN CONNECTION PLEASE CORRECT IT");
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GETRECActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
       new first().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_cmdExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicleInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicleInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicleInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicleInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicleInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GETREC;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdFirst;
    private javax.swing.JButton cmdLast;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdPrev;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    // End of variables declaration//GEN-END:variables
}
